const services = [
  {
    id: 1,
    name: "Dental Check-up",
    category: "Preventive & Diagnostic Care",
    description:
      "Routine examination to assess overall oral health and detect issues early.",
    image_url: "/images/services/dental-checkup.jpg",
    is_active: true,
    display_order: 1,
  },
  {
    id: 2,
    name: "X-ray",
    category: "Preventive & Diagnostic Care",
    description:
      "Dental imaging to identify hidden problems beneath teeth and gums.",
    image_url: "/images/services/xray.jpg",
    is_active: false,
    display_order: 2,
  },
  {
    id: 3,
    name: "Dental Cleaning (Scaling)",
    category: "Preventive & Diagnostic Care",
    description:
      "Removes plaque and tartar to keep gums healthy and prevent tooth decay.",
    image_url: "/images/services/dental-cleaning.jpg",
    is_active: true,
    display_order: 3,
  },
  {
    id: 4,
    name: "Composite Restoration (Posterior Teeth)",
    category: "Tooth Restoration",
    description:
      "Restores damaged back teeth with natural-looking composite material.",
    image_url: "/images/services/composite-posterior.jpg",
    is_active: true,
    display_order: 4,
  },
  {
    id: 5,
    name: "Composite Restoration (Anterior Teeth)",
    category: "Tooth Restoration",
    description: "Repairs front teeth while preserving a natural appearance.",
    image_url: "/images/services/composite-anterior.jpg",
    is_active: true,
    display_order: 5,
  },
  {
    id: 6,
    name: "Simple Extraction",
    category: "Tooth Extraction",
    description:
      "Removal of a tooth that cannot be saved due to damage or decay.",
    image_url: "/images/services/simple-extraction.jpg",
    is_active: true,
    display_order: 6,
  },
  {
    id: 7,
    name: "Surgical Extraction",
    category: "Tooth Extraction",
    description: "Advanced tooth removal for impacted or complicated cases.",
    image_url: "/images/services/surgical-extraction.jpg",
    is_active: true,
    display_order: 7,
  },
  {
    id: 8,
    name: "Wisdom Tooth Extraction",
    category: "Tooth Extraction",
    description:
      "Safe removal of problematic wisdom teeth to prevent pain and infection.",
    image_url: "/images/services/wisdom-extraction.jpg",
    is_active: true,
    display_order: 8,
  },
  {
    id: 9,
    name: "Root Canal Treatment",
    category: "Root Canal Treatment",
    description:
      "Treats infected tooth pulp to relieve pain and save the tooth.",
    image_url: "/images/services/root-canal.jpg",
    is_active: false,
    display_order: 9,
  },
  {
    id: 10,
    name: "Root Canal Treatment (Wisdom Tooth)",
    category: "Root Canal Treatment",
    description: "Specialized root canal procedure for infected wisdom teeth.",
    image_url: "/images/services/rct-wisdom.jpg",
    is_active: true,
    display_order: 10,
  },
  {
    id: 11,
    name: "Metal Crown",
    category: "Crowns & Caps",
    description: "Durable metal cap to protect and strengthen damaged teeth.",
    image_url: "/images/services/metal-crown.jpg",
    is_active: true,
    display_order: 11,
  },
  {
    id: 12,
    name: "PFM Crown",
    category: "Crowns & Caps",
    description:
      "Porcelain-fused-to-metal crown combining strength and aesthetics.",
    image_url: "/images/services/pfm-crown.jpg",
    is_active: true,
    display_order: 12,
  },
  {
    id: 13,
    name: "Zirconia Crown",
    category: "Crowns & Caps",
    description:
      "High-strength, natural-looking crown for long-lasting results.",
    image_url: "/images/services/zirconia-crown.jpg",
    is_active: true,
    display_order: 13,
  },
  {
    id: 14,
    name: "Braces (Orthodontic Treatment)",
    category: "Orthodontics",
    description: "Aligns teeth gradually to improve bite and smile appearance.",
    image_url: "/images/services/braces.jpg",
    is_active: true,
    display_order: 14,
  },
  {
    id: 15,
    name: "Teeth Whitening",
    category: "Cosmetic Dentistry",
    description: "Brightens teeth safely for a whiter, more confident smile.",
    image_url: "/images/services/teeth-whitening.jpg",
    is_active: true,
    display_order: 15,
  },
  {
    id: 16,
    name: "Denture (Partial / Complete)",
    category: "Dentures",
    description: "Custom-made dentures to restore function and appearance.",
    image_url: "/images/services/denture.jpg",
    is_active: true,
    display_order: 16,
  },
];

export default services;
